Move thread activation to start method
pytest-dev/pytest-django pull request #1032
Opened 2022-10-06 03:17 UTC by samamorgan

This moves activation of `LiveServer.thread` to a method. My primary motivation here is to delay thread activation so I can change the parameters of the thread in an overriden `live_server` fixture. This provides a work-around to issue #294 using the following override:

```python
import pytest
from pytest_django import live_server_helper
from pytest_django.lazy_django import skip_if_no_django

@pytest.fixture(scope="session")
def live_server(request):
    skip_if_no_django()

    addr = (
        request.config.getvalue("liveserver")
        or os.getenv("DJANGO_LIVE_TEST_SERVER_ADDRESS")
        or "localhost"
    )

    server = live_server_helper.LiveServer(addr)
    server.thread.static_handler = _StaticFilesHandler
    server.start()
    request.addfinalizer(server.stop)

    return server
```

2022-10-06 15:43 UTC, samamorgan commented
Note: The failing tests here aren't failing, it's just an issue with the codecov upload.

2022-10-06 19:03 UTC, bluetech requested changes
I'm not opposed to this, but needs a couple of changes:

1. To keep backward compat (not that it's a public interface, but who knows), let's add a `*, start: bool = True` argument to `__init__`, and add a call to `self.start` if `start` is true. You will then need to pass `start=False`.
2. The `inc_thread_sharing` part needs to be done in `start`, not in `__init__`, to match the `stop`.

2022-10-11 17:23 UTC, samamorgan commented
> I'm not opposed to this, but needs a couple of changes:
> 
> 1. To keep backward compat (not that it's a public interface, but who knows), let's add a `*, start: bool = True` argument to `__init__`, and add a call to `self.start` if `start` is true. You will then need to pass `start=False`.
> 2. The `inc_thread_sharing` part needs to be done in `start`, not in `__init__`, to match the `stop`.

Thanks for the quick feedback! I did both of these, then went a little ham and took it a step beyond.

This code was a little smelly. Imports inside the constructor, messing around with threads, etc. I refactored it to move all imports to the top, and it's now subclassing `LiveServerThread` rather than implementing a thread internally. This is functionally the same, but cleans up a lot of unnecessary calls to `self.thread`/`live_server.thread`. The class behaves like a thread, so why not just make it one?

If I went too hard here, I'm happy to back off and just implement the requested changes.

2022-10-11 17:38 UTC, samamorgan commented
Alright, tests failing now. Looks like I'm misunderstanding something about these imports. Is there an explanation I missed somewhere about why imports are happening in a function instead of the top of the module?

2022-10-11 18:15 UTC, bluetech commented
importing `django` has some side-effects, sometimes it requires `DJANGO_SETTINGS_MODULE` and such to be defined, etc. So it must always be imported lazily in pytest-django.

2022-10-18 23:17 UTC, samamorgan commented
Backed off on the subclassing decision. I spent _way too much time_ trying to implement a lazy import mechanism just to have it fall on its face.

I very much dislike the imports inside methods. Makes my heart hurt. I don't know enough about this library to really understand what a good alternative would be though, so the code smells get to stay!

2022-10-28 16:32 UTC, samamorgan commented
@bluetech Anything blocking this one?

2023-10-25 21:23 UTC, bluetech commented on pytest_django/fixtures.py
> +
```suggestion
```

2023-10-25 21:23 UTC, bluetech commented on pytest_django/live_server_helper.py
> +            port = 0
I think the entire `liveserver_kwargs` business was to avoid this line, i.e. not duplicate Django's default in case it changes.

2023-10-25 22:17 UTC, bluetech commented
Thanks @samamorgan. I rebased and removed unrelated changes from the diff. Merging now.

2023-10-25 22:17 UTC, merged